[package]
name = "dev_tools"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1.19.0"
sdl2 = { version = "0.37", features = ["image", "ttf", "mixer"] }

dev_macros = { path = "dev_macros" }